Add requirem and provides attr to RpmUnit
release-engineering/pubtools-pulplib pull request #139
Opened 2021-11-26 15:59 UTC by rbikar

TODO

2021-11-30 00:36 UTC, rohanpm requested changes

2021-11-30 00:36 UTC, rohanpm commented on pubtools/pulplib/_impl/model/unit/rpm.py
> +    List of capabilities that this RPM provides or ``None`` if this information is unavailable.
The doc strings for requires/provides seem to be the wrong way around.

2021-11-30 00:36 UTC, rohanpm commented on pubtools/pulplib/__init__.py
> +    Dependency,
Could this class please be named in a way which shows it's RPM-specific?  e.g. RpmDependency?

The concern is that other types of data can also have dependencies and we may need to support those some day, but this Dependency class wouldn't be usable for them.

2021-11-30 00:36 UTC, rohanpm commented on pubtools/pulplib/_impl/fake/rpmlib.py
> +            "epoch": None,  # unsure how to get this value from rpm headers
I think this ought to be fixed.  I looked for an RPM with non-zero epoch dependency and I think this info is also in the REQUIREVERSION field?

```
$ rpm -qp FreeWnn-devel-1.10pl020-6.el4.x86_64.rpm --requires
warning: FreeWnn-devel-1.10pl020-6.el4.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID db42a60e: NOKEY
FreeWnn-libs = 1:1.10pl020-6.el4
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1

$ rpm -qp FreeWnn-devel-1.10pl020-6.el4.x86_64.rpm --queryformat '%{REQUIREVERSION}'
warning: FreeWnn-devel-1.10pl020-6.el4.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID db42a60e: NOKEY
1:1.10pl020-6.el4
```

So I think the "vr" variable right now is actually "evr", with the "e" component frequently omitted.

2021-11-30 17:15 UTC, rbikar commented
Addressed all requested changes + added some more docstrings.

2021-11-30 21:42 UTC, rohanpm approved these changes

2021-11-30 21:42 UTC, rohanpm commented on pubtools/pulplib/_impl/model/unit/rpm.py
> +    List of dependecies that this RPM requires or ``None`` if this information is unavailable.
```suggestion
    List of dependencies that this RPM requires or ``None`` if this information is unavailable.
```

2021-12-01 08:24 UTC, rbikar commented
Fixed typo, I'll squash commits and carry +1s over.

2021-12-01 08:25 UTC, merged